---
functional:
  - Поддержка всех популярных языков программирования
  - Возможность выбора языка программирования в терминале баттла
  - Возможность авторизации через Github
  - Возможность авторизации и голосового чата через Discord
  - Ведение рейтинга игроков по неделе/месяцу/всего и отображение на главной странице. Возможность сортировки п орейтингу, количеству игр и т.д.
  - Возможность просмотра истории баттлов.
  - Возможность просмотра повтора баттла.
  - Возможность кастомизации при создании лобби - сложность, задача, теги и временной лимит
  - Мультиязычность задач (русский и английский)
  - Уведомление о начале баттла
  - Возможность просмотра баттла зрителям в режиме online
  - Возможность организации турниров и турнирной сетки
  - Возможность переподключения участника к баттлу
  - После определения победителя должна быть возможность остаться в баттле и дописать код / ознакомиться с кодом
  - В истории есть иконка напротив никнейма, указывающая на победителя баттла
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - На сайте должен быть минимальный лаг при наборе кода
  - У сайта должна быть удобная и быстрая регистрация
  - Оформление сайта должно быть безопасным(удобным) для глаз, особенно в ночное время
implicit:
  - Участник не может писать и изменять код соперника
  - Зрители не могут писать код и вносить изменения в код участников
  - Пользователи не могут вносить изменения в таблицу лидеров вручную
  - Участники не могут вносить изменения в предустановленную задачу баттла