---
functional:
  - Возможность выбора языка программирования в терминале баттла
  - Возможность кастомизации при создании баттла - сложность, задача, теги и временной лимит
  - Возможность отменить созданный баттл при отсутствии оппонента
  - Возможность участвовать только в одном баттле одновременно
  - Возможность регистрации с указанием email и созданием пароля
  - Email пользователя не может содержать пустые (невидимые) символы
  - Пароль пользователя должен быть не короче 6 символов
  - Пароль может содержать только буквы латинского алфавита и цифры
  - В пароле обязательно должны присутствовать как минимум 1 латинская буква и 1 цифра
  - Никнейм пользователя не может повторяться с уже зарегистрированными
  - Никнейм пользователя не должен быть пустым (невидимым)
  - Возможность авторизации с помощью email и пароля
  - Возможность авторизации с помощью своего аккаунта на Github
  - Ведение таблицы игроков-лидеров по неделе/месяцу/всего
  - Таблица игроков-лидеров должна отображаться на главной странице
  - Возможность сортировки таблицы лидеров по рейтингу, количеству игр и т.д.
  - Возможность отправлять приглашение на баттл другим пользователям
  - Возможность просмотра истории баттлов.
  - Возможность просмотра повтора баттла.
  - Мультиязычность задач (русский и английский)
  - Возможность просмотра баттла зрителям в режиме online
  - Возможность организации турниров и турнирной сетки
  - Возможность пользователя присоединиться к турниру
  - Возможность переподключения участника к баттлу
  - После определения победителя должна быть возможность остаться в баттле и дописать код / ознакомиться с кодом
  - В истории есть иконка напротив никнейма, указывающая на победителя баттла
  - На главной странице и в любом баттле есть чат, куда могут писать комментарии пользователи
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Весь текст на сайте должен быть написан понятным языком и не должен содержать орфографических/пунктуационных ошибок
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - На сайте должен быть минимальный лаг при наборе кода
  - У сайта должна быть удобная и быстрая регистрация
  - Оформление сайта должно быть безопасным (удобным) для глаз, особенно в ночное время
implicit:
  - Участник не может писать и изменять код соперника
  - Зрители не могут писать код и вносить изменения в код участников
  - Пользователи не могут вносить изменения в таблицу лидеров вручную
  - Участники не могут вносить изменения в предустановленную задачу баттла